export const mockListUtilities = {
  status: 'success',
  count: 3962,
  type: 'LoadServingEntity',
  results: [
    {
      lseId: 100776,
      name: 'Electricite de France S.A.',
      lseCode: 'EDFFR',
      code: '',
      websiteHome: 'https://www.edf.fr/',
      offeringType: 'Bundle',
      ownership: 'STATE',
      serviceTypes: 'ELECTRICITY',
      totalRevenues: null,
      totalSales: null,
      totalCustomers: 28500000,
      residentialServiceTypes: 'ELECTRICITY',
      residentialRevenues: null,
      residentialSales: null,
      residentialCustomers: null,
      commercialServiceTypes: 'ELECTRICITY',
      commercialRevenues: null,
      commercialSales: null,
      commercialCustomers: null,
      industrialServiceTypes: null,
      industrialRevenues: null,
      industrialSales: null,
      industrialCustomers: null,
      transportationServiceTypes: null,
      transportationRevenues: null,
      transportationSales: null,
      transportationCustomers: null,
      billingPeriodRepresentation: {
        fromDateOffset: 0,
        toDateOffset: 0,
        style: 'Unknown',
      },
    },
    {
      lseId: 100749,
      name: 'Korea Electric Power Corporation (KEPCO) ',
      lseCode: 'KEPCO',
      code: '',
      websiteHome: 'http://cyber.kepco.co.kr/kepco/EN/main.do',
      offeringType: 'Bundle',
      ownership: 'INVESTOR',
      serviceTypes: 'ELECTRICITY',
      totalRevenues: 32975000,
      totalSales: 394475000,
      totalCustomers: 18727411,
      residentialServiceTypes: 'ELECTRICITY',
      residentialRevenues: 6801500,
      residentialSales: 59427000,
      residentialCustomers: 12682652,
      commercialServiceTypes: 'ELECTRICITY',
      commercialRevenues: 15270600,
      commercialSales: 207216000,
      commercialCustomers: 337683,
      industrialServiceTypes: 'ELECTRICITY',
      industrialRevenues: 15270600,
      industrialSales: 207216000,
      industrialCustomers: 337683,
      transportationServiceTypes: null,
      transportationRevenues: null,
      transportationSales: null,
      transportationCustomers: null,
      billingPeriodRepresentation: {
        fromDateOffset: 0,
        toDateOffset: 0,
        style: 'Unknown',
      },
    },
    {
      lseId: 734,
      name: 'Pacific Gas & Electric Co',
      lseCode: 'PGE',
      code: '14328',
      websiteHome: 'http://www.pge.com/',
      offeringType: 'Bundle',
      ownership: 'INVESTOR',
      serviceTypes: 'ELECTRICITY',
      totalRevenues: 12615980,
      totalSales: 72481825,
      totalCustomers: 5069189,
      residentialServiceTypes: 'ELECTRICITY',
      residentialRevenues: 4969233,
      residentialSales: 27558981,
      residentialCustomers: 4453034,
      commercialServiceTypes: 'ELECTRICITY',
      commercialRevenues: 5057946,
      commercialSales: 27109514,
      commercialCustomers: 526484,
      industrialServiceTypes: 'ELECTRICITY',
      industrialRevenues: 2588801,
      industrialSales: 17813330,
      industrialCustomers: 89671,
      transportationServiceTypes: 'ELECTRICITY',
      transportationRevenues: 0,
      transportationSales: 0,
      transportationCustomers: 0,
      billingPeriodRepresentation: {
        fromDateOffset: 0,
        toDateOffset: -1,
        style: 'InclusiveToDate',
      },
    },
    {
      lseId: 1228,
      name: 'Southern California Edison Co',
      lseCode: 'SCE',
      code: '17609',
      websiteHome: 'http://www.sce.com/default.htm',
      offeringType: 'Bundle',
      ownership: 'INVESTOR',
      serviceTypes: 'ELECTRICITY',
      totalRevenues: 11650674,
      totalSales: 75438205,
      totalCustomers: 4990840,
      residentialServiceTypes: 'ELECTRICITY',
      residentialRevenues: 4961019,
      residentialSales: 30043784,
      residentialCustomers: 4375920,
      commercialServiceTypes: 'ELECTRICITY',
      commercialRevenues: 5814740,
      commercialSales: 38048580,
      commercialCustomers: 583092,
      industrialServiceTypes: 'ELECTRICITY',
      industrialRevenues: 863578,
      industrialSales: 7273080,
      industrialCustomers: 31827,
      transportationServiceTypes: 'ELECTRICITY',
      transportationRevenues: 11337,
      transportationSales: 72761,
      transportationCustomers: 1,
      billingPeriodRepresentation: {
        fromDateOffset: 0,
        toDateOffset: 0,
        style: 'GenabilityStyle',
      },
    },
    {
      lseId: 2654,
      name: 'Florida Power & Light Co',
      lseCode: 'FPL',
      code: '6452',
      websiteHome: 'http://www.fpl.com/index.shtml',
      offeringType: 'Bundle',
      ownership: 'INVESTOR',
      serviceTypes: 'ELECTRICITY',
      totalRevenues: 10717212,
      totalSales: 110326685,
      totalCustomers: 4708793,
      residentialServiceTypes: 'ELECTRICITY',
      residentialRevenues: 6298258,
      residentialSales: 59117632,
      residentialCustomers: 4169028,
      commercialServiceTypes: 'ELECTRICITY',
      commercialRevenues: 4207474,
      commercialSales: 48060597,
      commercialCustomers: 529349,
      industrialServiceTypes: 'ELECTRICITY',
      industrialRevenues: 203282,
      industrialSales: 3056252,
      industrialCustomers: 10415,
      transportationServiceTypes: 'ELECTRICITY',
      transportationRevenues: 8198,
      transportationSales: 92204,
      transportationCustomers: 1,
      billingPeriodRepresentation: {
        fromDateOffset: 0,
        toDateOffset: 0,
        style: 'Unknown',
      },
    },
    {
      lseId: 100357,
      name: 'Hydro Quebec',
      lseCode: 'HQ',
      code: '0',
      websiteHome: 'http://www.hydroquebec.com/',
      offeringType: 'Bundle',
      ownership: 'STATE',
      serviceTypes: 'ELECTRICITY',
      totalRevenues: 11736000,
      totalSales: 168401000,
      totalCustomers: 4107426,
      residentialServiceTypes: 'ELECTRICITY',
      residentialRevenues: 4825000,
      residentialSales: 65983000,
      residentialCustomers: 3821012,
      commercialServiceTypes: 'ELECTRICITY',
      commercialRevenues: 3504000,
      commercialSales: 44620000,
      commercialCustomers: 316585,
      industrialServiceTypes: 'ELECTRICITY',
      industrialRevenues: 2439000,
      industrialSales: 56900000,
      industrialCustomers: 186,
      transportationServiceTypes: 'ELECTRICITY',
      transportationRevenues: null,
      transportationSales: 0,
      transportationCustomers: 0,
      billingPeriodRepresentation: {
        fromDateOffset: 0,
        toDateOffset: 0,
        style: 'Unknown',
      },
    },
    {
      lseId: 100921,
      name: 'Liander',
      lseCode: 'LDR',
      code: '',
      websiteHome: 'https://www.liander.nl/',
      offeringType: 'Delivery',
      ownership: 'INVESTOR',
      serviceTypes: 'ELECTRICITY',
      totalRevenues: null,
      totalSales: null,
      totalCustomers: 3638000,
      residentialServiceTypes: 'ELECTRICITY',
      residentialRevenues: null,
      residentialSales: 13460600,
      residentialCustomers: null,
      commercialServiceTypes: 'ELECTRICITY',
      commercialRevenues: null,
      commercialSales: null,
      commercialCustomers: null,
      industrialServiceTypes: 'ELECTRICITY',
      industrialRevenues: null,
      industrialSales: null,
      industrialCustomers: null,
      transportationServiceTypes: null,
      transportationRevenues: null,
      transportationSales: null,
      transportationCustomers: null,
      billingPeriodRepresentation: {
        fromDateOffset: 0,
        toDateOffset: 0,
        style: 'Unknown',
      },
    },
    {
      lseId: 100926,
      name: 'Essent',
      lseCode: 'ES',
      code: '',
      websiteHome: 'https://www.essent.nl',
      offeringType: 'Energy',
      ownership: 'RETAIL_ENERGY_MARKETER',
      serviceTypes: 'ELECTRICITY',
      totalRevenues: null,
      totalSales: null,
      totalCustomers: 3100000,
      residentialServiceTypes: 'ELECTRICITY',
      residentialRevenues: null,
      residentialSales: 11470000,
      residentialCustomers: null,
      commercialServiceTypes: 'ELECTRICITY',
      commercialRevenues: null,
      commercialSales: null,
      commercialCustomers: null,
      industrialServiceTypes: null,
      industrialRevenues: null,
      industrialSales: null,
      industrialCustomers: null,
      transportationServiceTypes: null,
      transportationRevenues: null,
      transportationSales: null,
      transportationCustomers: null,
      billingPeriodRepresentation: {
        fromDateOffset: 0,
        toDateOffset: 0,
        style: 'Unknown',
      },
    },
    {
      lseId: 100920,
      name: 'Enexis',
      lseCode: 'ENEXIS',
      code: '',
      websiteHome: 'https://www.enexis.nl/consument/home',
      offeringType: 'Delivery',
      ownership: 'INVESTOR',
      serviceTypes: 'ELECTRICITY',
      totalRevenues: null,
      totalSales: null,
      totalCustomers: 2856000,
      residentialServiceTypes: 'ELECTRICITY',
      residentialRevenues: null,
      residentialSales: 10567200,
      residentialCustomers: null,
      commercialServiceTypes: 'ELECTRICITY',
      commercialRevenues: null,
      commercialSales: null,
      commercialCustomers: null,
      industrialServiceTypes: 'ELECTRICITY',
      industrialRevenues: null,
      industrialSales: null,
      industrialCustomers: null,
      transportationServiceTypes: null,
      transportationRevenues: null,
      transportationSales: null,
      transportationCustomers: null,
      billingPeriodRepresentation: {
        fromDateOffset: 0,
        toDateOffset: 0,
        style: 'Unknown',
      },
    },
    {
      lseId: 2252,
      name: 'Consolidated Edison Co-NY Inc',
      lseCode: 'ConEd',
      code: '4226',
      websiteHome: 'http://www.coned.com/',
      offeringType: 'Bundle',
      ownership: 'INVESTOR',
      serviceTypes: 'ELECTRICITY',
      totalRevenues: 4757588,
      totalSales: 20206464,
      totalCustomers: 2545762,
      residentialServiceTypes: 'ELECTRICITY',
      residentialRevenues: 2770915,
      residentialSales: 10534126,
      residentialCustomers: 2196201,
      commercialServiceTypes: 'ELECTRICITY',
      commercialRevenues: 1971958,
      commercialSales: 9584505,
      commercialCustomers: 349478,
      industrialServiceTypes: 'ELECTRICITY',
      industrialRevenues: 14420,
      industrialSales: 86327,
      industrialCustomers: 81,
      transportationServiceTypes: 'ELECTRICITY',
      transportationRevenues: 295,
      transportationSales: 1506,
      transportationCustomers: 2,
      billingPeriodRepresentation: {
        fromDateOffset: 0,
        toDateOffset: 0,
        style: 'Unknown',
      },
    },
  ],
  pageCount: 10,
  pageStart: 0,
};
